# Generated by Django 6.0.3 on 2026-05-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
