# Generated by Django 5.2.14 on 2026-05-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='send_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
