# Generated by Django 5.2.14 on 2026-05-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_emailverificationtoken_last_attempt_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
