# Generated by Django 6.0.4 on 2026-05-15 01:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaCancelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dias_anticipacion', models.PositiveIntegerField(help_text='Cancelando con al menos estos días de anticipación, se aplica este porcentaje de reembolso.')),
                ('porcentaje_reembolso', models.DecimalField(decimal_places=2, help_text='Porcentaje de reembolso (0-100).', max_digits=5)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Política de cancelación',
                'verbose_name_plural': 'Políticas de cancelación',
                'ordering': ['-dias_anticipacion'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=12, unique=True)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(blank=True, max_length=30)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('huespedes', models.PositiveIntegerField(default=1)),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255)),
                ('monto_reembolsado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('paypal', 'PayPal (simulado)')], default='tarjeta', max_length=20)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('referencia', models.CharField(max_length=40, unique=True)),
                ('titular', models.CharField(blank=True, max_length=150)),
                ('ultimos_4', models.CharField(blank=True, max_length=4)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
    ]
